import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, Matches, MinLength } from 'class-validator';

export class PayTransactionDto {
  /**
   * Payment token generated by Wompi.js on the frontend.
   * IMPORTANT: Never send raw card data (PAN, CVV, expiry) to the backend.
   * The frontend must tokenize the card using Wompi.js before calling this endpoint.
   */
  @ApiProperty({
    description:
      'Payment token from Wompi card tokenization. Must start with tok_',
    example: 'tok_stagtest_5113_4f7E8f2f0FbD44c8b8bE9bF5d2C3A1e0',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(10)
  @Matches(/^tok_/, {
    message: 'cardToken must be a valid Wompi token starting with tok_',
  })
  cardToken: string;
}
